# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzMkRcxlZsM-RElFESyqLGycU_OBjr4v
"""

from google.colab import files
uploaded = files.upload()

#!pip install openpyxl

import pandas as pd

# Load datasets
real_df = pd.read_excel("real_features.xlsx")
fake_df = pd.read_excel("fake_features_FINAL.xlsx")

# Add labels
real_df["label"] = 0   # Real
fake_df["label"] = 1   # Fake

# Merge
df = pd.concat([real_df, fake_df], ignore_index=True)

print("Final Shape:", df.shape)
df.head()

drop_cols = ["filename", "Original_File", "Duration"]

for col in drop_cols:
    if col in df.columns:
        df.drop(columns=[col], inplace=True)

print("Remaining Columns:", df.columns)

print("Final Shape:", df.shape)

df.head()

# Drop unnecessary columns
cols_to_drop = ["filename", "filename.1", "Label"]

for col in cols_to_drop:
    if col in df.columns:
        df.drop(columns=[col], inplace=True)

print("Columns after cleaning:\n", df.columns)

print(df.isnull().sum())

df = df.fillna(df.median())

print(df.columns)

X = df.drop("label", axis=1)
y = df["label"]

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scale
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train
rf = RandomForestClassifier(n_estimators=200, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)

# Predict
y_pred = rf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure()
sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

train_pred = rf.predict(X_train)
print("Train Accuracy:", accuracy_score(y_train, train_pred))

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=25,          # limit tree depth
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

# Train accuracy
train_pred = rf.predict(X_train)
print("Train Accuracy:", accuracy_score(y_train, train_pred))

# Test accuracy
y_pred = rf.predict(X_test)
print("Test Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf, X, y, cv=5)

print("Cross Validation Accuracy:", scores.mean())

import pandas as pd

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
}).sort_values(by="Importance", ascending=False)

importance.head(10)


import joblib

joblib.dump(rf, "voice_model.pkl")
joblib.dump(scaler, "scaler.pkl")

print("Model saved")