# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NzMkRcxlZsM-RElFESyqLGycU_OBjr4v
"""

from google.colab import files
uploaded = files.upload()

!pip install openpyxl

import pandas as pd

# Load datasets
real_df = pd.read_excel("real_features.xlsx")
fake_df = pd.read_excel("fake_features_FINAL.xlsx")

# Add labels
real_df["label"] = 0   # Real
fake_df["label"] = 1   # Fake

# Merge
df = pd.concat([real_df, fake_df], ignore_index=True)

print("Final Shape:", df.shape)
df.head()

drop_cols = ["filename", "Original_File", "Duration"]

for col in drop_cols:
    if col in df.columns:
        df.drop(columns=[col], inplace=True)

print("Remaining Columns:", df.columns)

print("Final Shape:", df.shape)

df.head()

# Drop unnecessary columns
cols_to_drop = ["filename", "filename.1", "Label"]

for col in cols_to_drop:
    if col in df.columns:
        df.drop(columns=[col], inplace=True)

print("Columns after cleaning:\n", df.columns)

print(df.isnull().sum())

df = df.fillna(df.median())

print(df.columns)

X = df.drop("label", axis=1)
y = df["label"]

!pip install xgboost

from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.1,
    random_state=42,
    n_jobs=-1
)

xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)

print("Train Accuracy:", accuracy_score(y_train, xgb.predict(X_train)))
print("Test Accuracy:", accuracy_score(y_test, y_pred))

xgb = XGBClassifier(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

from sklearn.model_selection import cross_val_score

scores = cross_val_score(xgb, X, y, cv=5)

print("CV Scores:", scores)
print("Mean CV Accuracy:", scores.mean())